### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by travanaft** [matildabrown/epidermalmorph#1] opened 2023-02-24 05:38 UTC
I can't install this package with devtools ('failed') or by installing the downloaded archive ('package' must be of length 1). Could you help me?

**Comment by matildabrown** [comment] 2023-02-24 08:48
Could you provide a copy of the full error message please, as well as the version and operating system that you are working on? This will help to pinpoint where the issue is. 

Thanks, 
Matilda

**Comment by travanaft** [comment] 2023-02-24 10:08
> devtools::install_github("matildabrown/epidermalmorph")
Downloading GitHub repo matildabrown/epidermalmorph@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet, :
download from 'https://api.github.com/repos/matildabrown/epidermalmorph/tarball/HEAD' failed

> library(epidermalmorph-main)
Error in library(epidermalmorph - main) : 'package' must be of length 1


R version 4.2.2
Windows 10

**Comment by matildabrown** [comment] 2023-02-24 10:15
Suggestions from: 
https://stackoverflow.com/questions/65421798/devtoolsinstall-github-failing-in-r4-0-03

Which version of devtools are you using? 
Could it be the a timeout? The package is reasonably large. 
Can you download and install other packages from GH? 

It doesn't look like it's causing the download, but once it's installed, use `library(epidermalmorph)` to load the package.

**Comment by travanaft** [comment] 2023-02-24 11:25
Thank you. Increasing the timeout time helped, it looks like the package is loaded

**Comment by matildabrown** [comment] 2023-02-24 11:49
Brilliant, glad it worked! Do get in touch with any other issues. 
Closing now.

**Closed as completed by matildabrown** 2023-02-24 11:49 UTC
